### ISSUE TITLE
./do.sh build_extension NoClassDefFoundError: com/google/javascript/jscomp/newtypes/ObjsType

### ISSUE THREAD

**Issue by rcchan** [google/end-to-end#264]
```
$ ./do.sh clean
Cleaning all builds...
removed `build/templates/cksum'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/backupkey/backupkey.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/backupkey'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/generic/generic.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/generic'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/importconfirmation/importconfirmation.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs/importconfirmation'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/dialogs'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/glass/glass.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/glass'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/panels/chipholder/chipholder.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels/chipholder'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/panels/generatekey/generatekey.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels/generatekey'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/panels/keyringmgmt/keyringmgmt.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels/keyringmgmt'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/panels/preferences/preferences.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels/preferences'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/panels/prompt/prompt.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels/prompt'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/panels'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/prompt/prompt.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/prompt'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/templates.soy.js'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/webview/webview.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/webview'
removed `build/templates/src/javascript/crypto/e2e/extension/ui/welcome/welcome.soy.js'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui/welcome'
removed directory: `build/templates/src/javascript/crypto/e2e/extension/ui'
removed directory: `build/templates/src/javascript/crypto/e2e/extension'
removed directory: `build/templates/src/javascript/crypto/e2e'
removed directory: `build/templates/src/javascript/crypto'
removed directory: `build/templates/src/javascript'
removed directory: `build/templates/src'
removed directory: `build/templates'
removed `build/test_js_deps-runfiles.js'
removed `build/deps.js'
removed directory: `build/extension'
removed directory: `build'
Done.

$ ./do.sh build_extension
All dependencies met.
All dependencies met.
Compiling Soy templates...
Done.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
Compiling JS files...
.java.lang.NoClassDefFoundError: com/google/javascript/jscomp/newtypes/ObjsType
	at com.google.javascript.jscomp.ClosureCodingConvention.getAssertionFunctions(ClosureCodingConvention.java:399)
	at com.google.javascript.jscomp.TypeInferencePass.<init>(TypeInferencePass.java:54)
	at com.google.javascript.jscomp.PassConfig.makeTypeInference(PassConfig.java:161)
	at com.google.javascript.jscomp.DefaultPassConfig$44$1.process(DefaultPassConfig.java:1417)
	at com.google.javascript.jscomp.PhaseOptimizer$NamedPass.process(PhaseOptimizer.java:285)
	at com.google.javascript.jscomp.PhaseOptimizer.process(PhaseOptimizer.java:217)
	at com.google.javascript.jscomp.Compiler.check(Compiler.java:844)
	at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:757)
	at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:95)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:656)
	at com.google.javascript.jscomp.Compiler$3.call(Compiler.java:653)
	at com.google.javascript.jscomp.Compiler$4.call(Compiler.java:700)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.google.javascript.jscomp.newtypes.ObjsType
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```

I've tried deleting `/lib` and reinstalling deps.

**Comment by adhintz** [comment]
What OS are you running? Building works fine for me, so I'm guessing it's an issue with a library.

$ ./do.sh build_extension
All dependencies met.
Using previous template build. Run ./do.sh clean if you want to rebuild the templates.
Building End-To-End extension to build/extension
Compiling JS files...
.....
Compiling CSS files...
Copying extension files...
Done.

**Comment by rcchan** [comment]
```
$ uname -a`
`Linux cslab5a 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux
```
```
$ java -version`
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by adhintz** [comment]
I'm on Ubuntu Trusty. Perhaps the latest Closure doesn't work with Sun's
Java. If so, maybe an older version of closure would work.

$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

**Comment by rcchan** [comment]
Tried it on Java 7 (found an installed version, changed `PATH` to match), still no go.
```
$ which java
/usr/lib/jvm/java-7-openjdk-amd64/bin/java

$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

The line about `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8` is because there's some weird (unicode?) characters in comments that cause a compile time error without it.

**Comment by rcchan** [comment]
Manually `cd`ing into `/lib/closure-compiler` and running `ant clean && ant` seems to have fixed the problem.  Perhaps there is an issue with how we're building it in `install_deps`.

**Comment by rcchan** [comment]
Dropping in `ant clean` into ./do.sh seems to resolve the issue for me.
It doesn't seem to do anything in particular (no delete messages) but makes everything work.

```
# build closure compiler
if [ ! -f closure-compiler/build/compiler.jar ]; then
  cd closure-compiler
  ant clean
  ant jar
  cd ..
fi
```
